# Generated by Django 4.1.9 on 2023-11-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='updated',
        ),
    ]
