# Generated by Django 4.1.9 on 2023-11-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_contact_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
