# Generated by Django 4.1.9 on 2023-11-13 14:24
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0014_remove_user_following'),
        ('account', '0005_profile_users_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_to',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-created'], name='account_pro_created_eba3ea_idx'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
