# Generated by Django 4.1.9 on 2023-11-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_contact_user_from_remove_contact_user_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='account_pro_created_eba3ea_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
    ]
