# Generated by Django 4.1.9 on 2023-11-13 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_alter_profile_options_profile_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='users_follow',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_follow',
            field=models.ManyToManyField(blank=True, related_name='user_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
