# Generated by Django 4.1.9 on 2023-11-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_profile_users_follow_profile_user_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-total_followers'], name='account_pro_total_f_9a9e95_idx'),
        ),
    ]
