# Generated by Django 4.1.9 on 2023-11-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_topic_fake_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='fake_field',
            new_name='fake_fieldddd',
        ),
    ]
