# Generated by Django 4.1.9 on 2023-11-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_fake_field_topic_fake_fieldddd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='fake_fieldddd',
        ),
    ]
