# Generated by Django 4.1.9 on 2023-11-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_rename_tags_topic_tags_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='tags_new',
            new_name='tags',
        ),
    ]
