# Generated by Django 4.1.9 on 2023-11-11 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0006_rename_tags_new_topic_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
