# Generated by Django 4.1.9 on 2023-11-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_topic_total_likes_alter_topic_users_like_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='topic',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['-date_added'], name='learning_lo_date_ad_d9e5bf_idx'),
        ),
    ]
