# Generated by Django 4.1.9 on 2023-12-26 04:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_remove_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, max_length=250, populate_from='text', unique=True),
            preserve_default=False,
        ),
    ]
